  Continuous-Deployment:
    needs: build-and-push-ecr-image
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::510706241095:role/GithubActions-mlproject
          role-session-name: gha-mlproject
          aws-region: ${{ env.AWS_REGION }}

      - name: Who am I?
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pull latest image
        run: docker pull ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest

      - name: Stop old container (if running)
        run: docker ps -q --filter "name=mltest" && docker rm -f mltest || true

      - name: Run Docker image
        # Your container serves on 5000; map host 8080 -> container 5000
        run: |
          docker run -d --name mltest \
            -p 8080:5000 \
            --ipc=host \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest

      - name: Clean previous images and containers
        run: docker system prune -f
